/**
 * TQQ Vault - Master Card Metadata Catalog
 * Contains card definitions spanning all 5 Nakano sisters and support characters
 * across all rarities (C, UC, R, SR, UR, SEC, MR), mapped to official artwork assets.
 */

import { CardDefinition, CharacterId, Rarity } from '../types/card';

export const CARDS_CATALOG: CardDefinition[] = [
  // ==========================================
  // 1. ICHIKA NAKANO (Eldest, Actress)
  // ==========================================
  {
    id: 'ichika_c_01',
    cardNumber: 'TQQ-001',
    characterId: 'ichika',
    characterRole: 'sister',
    name: 'Ichika Nakano',
    title: 'Morning Yawn',
    rarity: 'C',
    loreQuote: 'Five minutes more, Fuutarou-kun... Big sisters need their beauty sleep.',
    description: 'A candid snapshot of Ichika still tangled in her sheets before morning study session.',
    imageUrl: '/cards/Ichika/Ichika Tier ONE.jpg',
  },
  {
    id: 'ichika_uc_01',
    cardNumber: 'TQQ-002',
    characterId: 'ichika',
    characterRole: 'sister',
    name: 'Ichika Nakano',
    title: 'Audition Script in Hand',
    rarity: 'UC',
    loreQuote: 'I have to balance school and auditions. Neither can be treated half-heartedly.',
    description: 'Ichika memorizing her lines during lunch break with dog-eared script pages.',
    imageUrl: '/cards/Ichika/Ichika Tier TWO.jpg',
  },
  {
    id: 'ichika_r_01',
    cardNumber: 'TQQ-003',
    characterId: 'ichika',
    characterRole: 'sister',
    name: 'Ichika Nakano',
    title: 'Studio Spotlight',
    rarity: 'R',
    loreQuote: 'The camera doesn\'t lie, but an actress knows how to show only what she desires.',
    description: 'Ichika stepping onto her first television set as a rising starlet.',
    imageUrl: '/cards/Ichika/Ichika Tier Three.jpg',
  },
  {
    id: 'ichika_sr_01',
    cardNumber: 'TQQ-004',
    characterId: 'ichika',
    characterRole: 'sister',
    name: 'Ichika Nakano',
    title: 'Playful Tease',
    rarity: 'SR',
    loreQuote: 'You blushed just now, didn\'t you? Don\'t worry, big sister won\'t tell the others.',
    description: 'Ichika leaning dangerously close with her trademark wink in the library.',
    imageUrl: '/cards/Ichika/Ichika Tier four.jpg',
  },
  {
    id: 'ichika_ur_01',
    cardNumber: 'TQQ-005',
    characterId: 'ichika',
    characterRole: 'sister',
    name: 'Ichika Nakano',
    title: 'Red Carpet Radiance',
    rarity: 'UR',
    loreQuote: 'I stand here because you believed in me before anyone else knew my name.',
    description: 'Ichika dressed in an emerald gala gown, turning back towards the flashbulbs.',
    imageUrl: '/cards/Ichika/Ichika Tier fife.jpg',
  },
  {
    id: 'ichika_sec_01',
    cardNumber: 'TQQ-006',
    characterId: 'ichika',
    characterRole: 'sister',
    name: 'Ichika Nakano',
    title: 'Whispered Deception',
    rarity: 'SEC',
    loreQuote: 'Everything I said back then... what if none of it was acting?',
    description: 'A rain-soaked promenade where Ichika drops her composed facade.',
    imageUrl: '/cards/Ichika/Ichika Tier six.jpg',
  },
  {
    id: 'ichika_mr_01',
    cardNumber: 'TQQ-007',
    characterId: 'ichika',
    characterRole: 'sister',
    name: 'Ichika Nakano',
    title: 'The Eldest Bride',
    rarity: 'MR',
    loreQuote: 'As the eldest, I always stepped aside... but this hand, I will never let go.',
    description: 'Ichika in a flowing veil with gentle yellow roses, smiling with serene devotion.',
    imageUrl: '/cards/Ichika/Ichika Tier seven.jpg',
  },

  // ==========================================
  // 2. NINO NAKANO (Second, Chef/Tsundere)
  // ==========================================
  {
    id: 'nino_c_01',
    cardNumber: 'TQQ-008',
    characterId: 'nino',
    characterRole: 'sister',
    name: 'Nino Nakano',
    title: 'Afternoon Tea Disdain',
    rarity: 'C',
    loreQuote: 'Don\'t think this Earl Grey means I accept you as our tutor!',
    description: 'Nino sliding a saucer across the kitchen counter with crossed arms and a pout.',
    imageUrl: '/cards/Nino/Nino 1.jpg',
  },
  {
    id: 'nino_uc_01',
    cardNumber: 'TQQ-009',
    characterId: 'nino',
    characterRole: 'sister',
    name: 'Nino Nakano',
    title: 'Kitchen Alchemist',
    rarity: 'UC',
    loreQuote: 'Cooking is precision. If the temperature drops by two degrees, the soufflé dies.',
    description: 'Nino in her frilled apron meticulously whipping fresh cream to stiff peaks.',
    imageUrl: '/cards/Nino/nino 2.jpg',
  },
  {
    id: 'nino_r_01',
    cardNumber: 'TQQ-010',
    characterId: 'nino',
    characterRole: 'sister',
    name: 'Nino Nakano',
    title: 'Twin Ribbons of Defiance',
    rarity: 'R',
    loreQuote: 'I protect this family. Anyone who tries to break our bond will answer to me.',
    description: 'Nino with her iconic black twin ribbons fluttering as she stands her ground.',
    imageUrl: '/cards/Nino/nino 3.jpg',
  },
  {
    id: 'nino_sr_01',
    cardNumber: 'TQQ-011',
    characterId: 'nino',
    characterRole: 'sister',
    name: 'Nino Nakano',
    title: 'Unstoppable Locomotive',
    rarity: 'SR',
    loreQuote: 'I won\'t play mind games like Ichika or hesitate like Miku. I love you, idiot!',
    description: 'Nino turning around on the back of the motorcycle, delivering her unfiltered confession.',
    imageUrl: '/cards/Nino/nino 4.jpg',
  },
  {
    id: 'nino_ur_01',
    cardNumber: 'TQQ-012',
    characterId: 'nino',
    characterRole: 'sister',
    name: 'Nino Nakano',
    title: 'Pâtisserie Fleur',
    rarity: 'UR',
    loreQuote: 'Every pastry I bake holds a piece of our shared memories.',
    description: 'Nino as master chef in her boutique bakery surrounded by strawberry tarts and macarons.',
    imageUrl: '/cards/Nino/nino 5.jpg',
  },
  {
    id: 'nino_sec_01',
    cardNumber: 'TQQ-013',
    characterId: 'nino',
    characterRole: 'sister',
    name: 'Nino Nakano',
    title: 'Seven Scars Hotelier',
    rarity: 'SEC',
    loreQuote: 'Even if my heart breaks a thousand times, I will always choose to love fiercely.',
    description: 'Nino under the hotel veranda lights after shearing her long locks into a chic bob.',
    imageUrl: '/cards/Nino/nino 6.jpg',
  },
  {
    id: 'nino_mr_01',
    cardNumber: 'TQQ-014',
    characterId: 'nino',
    characterRole: 'sister',
    name: 'Nino Nakano',
    title: 'The Passionate Bride',
    rarity: 'MR',
    loreQuote: 'You made me wait, Fuu-kun. Now spend the rest of your life making it up to me.',
    description: 'Nino wearing an extravagant lace wedding dress adorned with twin silk ribbons.',
    imageUrl: '/cards/Nino/nino 7.jpg',
  },

  // ==========================================
  // 3. MIKU NAKANO (Third, Sengoku/Cardigan)
  // ==========================================
  {
    id: 'miku_c_01',
    cardNumber: 'TQQ-015',
    characterId: 'miku',
    characterRole: 'sister',
    name: 'Miku Nakano',
    title: 'Headphones On, World Off',
    rarity: 'C',
    loreQuote: 'Please keep your voice down... I am listening to the Battle of Sekigahara lecture.',
    description: 'Miku resting her chin inside her soft blue cardigan, blue triangular headphones secured.',
    imageUrl: '/cards/Miku/miku 1.jpg',
  },
  {
    id: 'miku_uc_01',
    cardNumber: 'TQQ-016',
    characterId: 'miku',
    characterRole: 'sister',
    name: 'Miku Nakano',
    title: 'Green Tea & Warlords',
    rarity: 'UC',
    loreQuote: 'Takeda Shingen and Uesugi Kenshin fought five times at Kawanakajima. True devotion.',
    description: 'Miku clutching a warm can of green matcha tea while quizzing Fuutarou on Sengoku trivia.',
    imageUrl: '/cards/Miku/miku 2.jpg',
  },
  {
    id: 'miku_r_01',
    cardNumber: 'TQQ-017',
    characterId: 'miku',
    characterRole: 'sister',
    name: 'Miku Nakano',
    title: 'Crooked Bread Loaf',
    rarity: 'R',
    loreQuote: 'It may look charred on the bottom, but... taste it. I made it just for you.',
    description: 'Miku presenting a slightly burned loaf of matcha bread with flour dusted on her cheek.',
    imageUrl: '/cards/Miku/miku 3.jpg',
  },
  {
    id: 'miku_sr_01',
    cardNumber: 'TQQ-018',
    characterId: 'miku',
    characterRole: 'sister',
    name: 'Miku Nakano',
    title: 'Pointed Finger of Truth',
    rarity: 'SR',
    loreQuote: 'You... you\'re Fuutarou! See? I knew who you were even without looking.',
    description: 'Miku extending her hand on the school roof terrace, unmasking Fuutarou\'s disguise.',
    imageUrl: '/cards/Miku/miku 4.jpg',
  },
  {
    id: 'miku_ur_01',
    cardNumber: 'TQQ-019',
    characterId: 'miku',
    characterRole: 'sister',
    name: 'Miku Nakano',
    title: 'Culinary Masterwork',
    rarity: 'UR',
    loreQuote: 'I started from zero. If I can master French baking, I can win your heart too.',
    description: 'Miku presenting a flawless three-tier matcha opera cake alongside Nino in their bistro.',
    imageUrl: '/cards/Miku/miku 5.jpg',
  },
  {
    id: 'miku_sec_01',
    cardNumber: 'TQQ-020',
    characterId: 'miku',
    characterRole: 'sister',
    name: 'Miku Nakano',
    title: 'Sengoku General\'s Resolve',
    rarity: 'SEC',
    loreQuote: 'Like the warriors of old, I staked everything on one decisive march.',
    description: 'Miku enveloped in falling cherry blossoms beneath Kyoto\'s historic pagoda temples.',
    imageUrl: '/cards/Miku/miku 6.jpg',
  },
  {
    id: 'miku_mr_01',
    cardNumber: 'TQQ-021',
    characterId: 'miku',
    characterRole: 'sister',
    name: 'Miku Nakano',
    title: 'The Sengoku Bride',
    rarity: 'MR',
    loreQuote: 'My heart belongs to you, in this life and across all historical eras.',
    description: 'Miku in an exquisite indigo-trimmed silk bridal kimono holding a white folding fan.',
    imageUrl: '/cards/Miku/miku 7.jpg',
  },

  // ==========================================
  // 4. YOTSUBA NAKANO (Fourth, Athlete/Ribbon)
  // ==========================================
  {
    id: 'yotsuba_c_01',
    cardNumber: 'TQQ-022',
    characterId: 'yotsuba',
    characterRole: 'sister',
    name: 'Yotsuba Nakano',
    title: 'Trackside Dash',
    rarity: 'C',
    loreQuote: 'Uesugi-san! Need help carrying those textbooks? I have plenty of stamina!',
    description: 'Yotsuba jogging backwards across the track field, bright green ribbon bouncing.',
    imageUrl: '/cards/Yotsuba/yotsu 1.jpg',
  },
  {
    id: 'yotsuba_uc_01',
    cardNumber: 'TQQ-023',
    characterId: 'yotsuba',
    characterRole: 'sister',
    name: 'Yotsuba Nakano',
    title: 'Class Representative Duties',
    rarity: 'UC',
    loreQuote: 'Someone needed to volunteer, so I stepped up! Helping others makes me happy.',
    description: 'Yotsuba carrying four armfuls of sports festival banners with an earnest grin.',
    imageUrl: '/cards/Yotsuba/yotsu 2.jpg',
  },
  {
    id: 'yotsuba_r_01',
    cardNumber: 'TQQ-024',
    characterId: 'yotsuba',
    characterRole: 'sister',
    name: 'Yotsuba Nakano',
    title: 'Ferris Wheel Confession Check',
    rarity: 'R',
    loreQuote: 'I like you, Uesugi-san! ...Just kidding, ehehe! Did your heart skip a beat?',
    description: 'Yotsuba resting against the glass gondola high above the sunset amusement park.',
    imageUrl: '/cards/Yotsuba/yotsu 3.jpg',
  },
  {
    id: 'yotsuba_sr_01',
    cardNumber: 'TQQ-025',
    characterId: 'yotsuba',
    characterRole: 'sister',
    name: 'Yotsuba Nakano',
    title: 'Swing Set Launch',
    rarity: 'SR',
    loreQuote: 'If you want to clear your head, you have to jump as far as humanly possible!',
    description: 'Yotsuba soaring through the twilight air off the playground swing with boundless glee.',
    imageUrl: '/cards/Yotsuba/yotsu 4.jpg',
  },
  {
    id: 'yotsuba_ur_01',
    cardNumber: 'TQQ-026',
    characterId: 'yotsuba',
    characterRole: 'sister',
    name: 'Yotsuba Nakano',
    title: 'Six Years of Hidden Tears',
    rarity: 'UR',
    loreQuote: 'I promised myself I would support my sisters, even if it meant burying my own heart.',
    description: 'Yotsuba clutching her green ribbon under the Kyoto rain, tears streaming down her smiling face.',
    imageUrl: '/cards/Yotsuba/yotsu 5.jpg',
  },
  {
    id: 'yotsuba_sec_01',
    cardNumber: 'TQQ-027',
    characterId: 'yotsuba',
    characterRole: 'sister',
    name: 'Yotsuba Nakano',
    title: 'The Bell Tower Oath',
    rarity: 'SEC',
    loreQuote: 'The bell rang for us that snowy afternoon... an unbreakable promise etched in time.',
    description: 'The silhouette beneath the resort bell tower amidst swirling snowflakes.',
    imageUrl: '/cards/Yotsuba/yotsu 6.jpg',
  },
  {
    id: 'yotsuba_mr_01',
    cardNumber: 'TQQ-028',
    characterId: 'yotsuba',
    characterRole: 'sister',
    name: 'Yotsuba Nakano',
    title: 'The Chosen Bride',
    rarity: 'MR',
    loreQuote: 'Thank you for finding me, Fuutarou. From Kyoto until forever, I am yours.',
    description: 'Yotsuba radiant in a pure white gown woven with clover filigree, holding Fuutarou\'s hand.',
    imageUrl: '/cards/Yotsuba/yotsu 7.jpg',
  },

  // ==========================================
  // 5. ITSUKI NAKANO (Fifth, Foodie/Star-pins)
  // ==========================================
  {
    id: 'itsuki_c_01',
    cardNumber: 'TQQ-029',
    characterId: 'itsuki',
    characterRole: 'sister',
    name: 'Itsuki Nakano',
    title: 'Meat Bun Delight',
    rarity: 'C',
    loreQuote: 'Eating properly is fundamental for cognitive retention! Nom... delicious!',
    description: 'Itsuki biting into a steaming pork bun outside the convenience store with puffed cheeks.',
    imageUrl: '/cards/Itsuki/istu 1.jpg',
  },
  {
    id: 'itsuki_uc_01',
    cardNumber: 'TQQ-030',
    characterId: 'itsuki',
    characterRole: 'sister',
    name: 'Itsuki Nakano',
    title: 'Star-Pinned Focus',
    rarity: 'UC',
    loreQuote: 'Mother was an educator. I will not tarnish her legacy by giving up on these equations.',
    description: 'Itsuki adjusting her twin star hairpins before diving into a thick chemistry workbook.',
    imageUrl: '/cards/Itsuki/itsu 2.jpg',
  },
  {
    id: 'itsuki_r_01',
    cardNumber: 'TQQ-031',
    characterId: 'itsuki',
    characterRole: 'sister',
    name: 'Itsuki Nakano',
    title: 'Midnight Moonlit Study',
    rarity: 'R',
    loreQuote: 'Uesugi-kun, you worked so hard preparing these flashcards... I won\'t let them go to waste.',
    description: 'Itsuki studying at Fuutarou\'s modest dining table under the warm glow of a desk lamp.',
    imageUrl: '/cards/Itsuki/itsu 3.jpg',
  },
  {
    id: 'itsuki_sr_01',
    cardNumber: 'TQQ-032',
    characterId: 'itsuki',
    characterRole: 'sister',
    name: 'Itsuki Nakano',
    title: 'Renaissance Festival Feast',
    rarity: 'SR',
    loreQuote: 'Five plates of yakisoba, three crepes, and two melon breads. That constitutes a light snack.',
    description: 'Itsuki balancing three food trays at the school festival with an angelic satisfied expression.',
    imageUrl: '/cards/Itsuki/itsu 4.jpg',
  },
  {
    id: 'itsuki_ur_01',
    cardNumber: 'TQQ-033',
    characterId: 'itsuki',
    characterRole: 'sister',
    name: 'Itsuki Nakano',
    title: 'Sensei\'s Chalkboard',
    rarity: 'UR',
    loreQuote: 'Just as you guided us five, I will stand before the classroom and light the way for others.',
    description: 'Itsuki standing tall at the lecture podium with chalk in hand, fulfilling her mother\'s dream.',
    imageUrl: '/cards/Itsuki/itsu 5.jpg',
  },
  {
    id: 'itsuki_sec_01',
    cardNumber: 'TQQ-034',
    characterId: 'itsuki',
    characterRole: 'sister',
    name: 'Itsuki Nakano',
    title: 'Echo of Rena',
    rarity: 'SEC',
    loreQuote: 'The girl from your past wished you happiness. Now, as Itsuki, I wish for the same.',
    description: 'Itsuki standing by the serene lake at sunset, the hat of "Rena" resting in her hands.',
    imageUrl: '/cards/Itsuki/itsu 6.jpg',
  },
  {
    id: 'itsuki_mr_01',
    cardNumber: 'TQQ-035',
    characterId: 'itsuki',
    characterRole: 'sister',
    name: 'Itsuki Nakano',
    title: 'The Destiny Bride',
    rarity: 'MR',
    loreQuote: 'We met over cafeteria food, clashed over pride, and grew into an eternal bond.',
    description: 'Itsuki in a regal bridal gown with shimmering star embroidery and a crimson rose bouquet.',
    imageUrl: '/cards/Itsuki/itsu 7.jpg',
  },

  // ==========================================
  // 6. FUUTAROU UESUGI (The Tutor / Support)
  // ==========================================
  {
    id: 'fuutarou_r_01',
    cardNumber: 'TQQ-036',
    characterId: 'fuutarou',
    characterRole: 'support',
    name: 'Fuutarou Uesugi',
    title: 'The 100-Point Tutor',
    rarity: 'R',
    loreQuote: 'If you combine all five of your scores... congratulations, you barely scored 100 points total.',
    description: 'Fuutarou holding five failing test papers while nursing a pounding headache.',
    imageUrl: '/cards/Futarou/futa 1.jpg',
  },
  {
    id: 'fuutarou_sr_01',
    cardNumber: 'TQQ-037',
    characterId: 'fuutarou',
    characterRole: 'support',
    name: 'Fuutarou Uesugi',
    title: 'Legendary Photograph',
    rarity: 'SR',
    loreQuote: 'A photo kept inside a student handbook for five long years. The boy who promised to study.',
    description: 'The faded childhood photograph taken in Kyoto between Fuutarou and a mysterious girl.',
    imageUrl: '/cards/Futarou/futa 2.jpg',
  },
  {
    id: 'fuutarou_ur_01',
    cardNumber: 'TQQ-038',
    characterId: 'fuutarou',
    characterRole: 'support',
    name: 'Fuutarou Uesugi',
    title: 'The Determined Groom',
    rarity: 'UR',
    loreQuote: 'I used to think study was everything. You five taught me that people are what truly matter.',
    description: 'Fuutarou standing at the chapel altar in a pristine white tuxedo, awaiting his bride.',
    imageUrl: '/cards/Futarou/futa 3.jpg',
  },
  {
    id: 'fuutarou_sec_01',
    cardNumber: 'TQQ-039',
    characterId: 'fuutarou',
    characterRole: 'support',
    name: 'Fuutarou Uesugi',
    title: 'Full Marks Across Five',
    rarity: 'SEC',
    loreQuote: 'Every single one of you passed. Not one left behind. We did it together.',
    description: 'Fuutarou shedding rare tears of relief as five graduation diplomas are displayed together.',
    imageUrl: '/cards/Futarou/futa 3.jpg',
  },

  // ==========================================
  // 7. RAIHA UESUGI (Little Sister / Lucky Charm)
  // ==========================================
  {
    id: 'raiha_uc_01',
    cardNumber: 'TQQ-040',
    characterId: 'raiha',
    characterRole: 'support',
    name: 'Raiha Uesugi',
    title: 'Sunny Smile',
    rarity: 'UC',
    loreQuote: 'Onii-chan! The Nakano sisters are here! Be nice to them or I won\'t make hamburg steak!',
    description: 'Raiha welcoming the quints into the Uesugi household with her infectious grin.',
    imageUrl: '/cards/Raiha/raiha 1.jpg',
  },
  {
    id: 'raiha_r_01',
    cardNumber: 'TQQ-041',
    characterId: 'raiha',
    characterRole: 'support',
    name: 'Raiha Uesugi',
    title: 'Lucky Charm Arc',
    rarity: 'R',
    loreQuote: 'When Raiha is around, good fortunes always follow! Even grumpy Onii-chan smiles.',
    description: 'Raiha holding up handcrafted omamori lucky charms for all five sisters.',
    imageUrl: '/cards/Raiha/raiha 2.jpg',
  },
  {
    id: 'raiha_sr_01',
    cardNumber: 'TQQ-042',
    characterId: 'raiha',
    characterRole: 'support',
    name: 'Raiha Uesugi',
    title: 'Little Sister\'s Blessing',
    rarity: 'SR',
    loreQuote: 'Whichever sister Onii-chan chooses, I will be the happiest little sister in Japan!',
    description: 'Raiha serving hot piping curry at the dinner table with five extra place settings.',
    imageUrl: '/cards/Raiha/raiha 2.jpg',
  },

  // ==========================================
  // 8. MARUO NAKANO (Strict Father / Examiner)
  // ==========================================
  {
    id: 'maruo_r_01',
    cardNumber: 'TQQ-043',
    characterId: 'maruo',
    characterRole: 'support',
    name: 'Maruo Nakano',
    title: 'Hospital Director',
    rarity: 'R',
    loreQuote: 'Failing grades are unacceptable. If they fail the midterm, you are dismissed immediately.',
    description: 'Maruo inspecting medical charts through his silver rimless spectacles with cold authority.',
    imageUrl: '/cards/Maruo/maru 1.jpg',
  },
  {
    id: 'maruo_sr_01',
    cardNumber: 'TQQ-044',
    characterId: 'maruo',
    characterRole: 'support',
    name: 'Maruo Nakano',
    title: 'The Unyielding Father',
    rarity: 'SR',
    loreQuote: 'I may not speak with warmth, but their future is the only thing I have sworn to safeguard.',
    description: 'Maruo sitting in the back of his executive limousine, observing his daughters from afar.',
    imageUrl: '/cards/Maruo/maru 1.jpg',
  },
  {
    id: 'maruo_ur_01',
    cardNumber: 'TQQ-045',
    characterId: 'maruo',
    characterRole: 'support',
    name: 'Maruo Nakano',
    title: 'A Father\'s Silent Blessing',
    rarity: 'UR',
    loreQuote: 'Uesugi-kun... take care of my daughter. You have earned my begrudging respect.',
    description: 'Maruo raising a ceremonial toast at the reception with a faint, proud smile.',
    imageUrl: '/cards/Maruo/maru 1.jpg',
  },

  // ==========================================
  // 9. ISANARI UESUGI (Fuutarou\'s Father)
  // ==========================================
  {
    id: 'isanari_uc_01',
    cardNumber: 'TQQ-046',
    characterId: 'isanari',
    characterRole: 'support',
    name: 'Isanari Uesugi',
    title: 'Wild Motorcyclist',
    rarity: 'UC',
    loreQuote: 'Youth is for riding full throttle! Don\'t get old before your time, Fuutarou!',
    description: 'Isanari in his leather jacket, giving a thumbs up beside his vintage motorcycle.',
    imageUrl: '/cards/isanari/isa 1.jpg',
  },
  {
    id: 'isanari_r_01',
    cardNumber: 'TQQ-047',
    characterId: 'isanari',
    characterRole: 'support',
    name: 'Isanari Uesugi',
    title: 'Old Days Rebel',
    rarity: 'R',
    loreQuote: 'Maruo and I go way back! That stiff-collared doctor used to have quite the temper himself!',
    description: 'Isanari laughing boisterously while recounting nostalgic schoolboy rivalry stories.',
    imageUrl: '/cards/isanari/isa 1.jpg',
  },

  // ==========================================
  // 10. YUSUKE TAKEDA (Academic Rival)
  // ==========================================
  {
    id: 'takeda_c_01',
    cardNumber: 'TQQ-048',
    characterId: 'takeda',
    characterRole: 'support',
    name: 'Yusuke Takeda',
    title: 'Aspiring Astronaut',
    rarity: 'C',
    loreQuote: 'My gaze is fixed upon outer space! A mere high school mock exam is just one small step.',
    description: 'Takeda pointing dramatically toward the celestial cosmos from the rooftop observatory.',
    imageUrl: '/cards/Yusuke/yusuke 1.jpg',
  },
  {
    id: 'takeda_uc_01',
    cardNumber: 'TQQ-049',
    characterId: 'takeda',
    characterRole: 'support',
    name: 'Yusuke Takeda',
    title: 'National Mock Exam Rival',
    rarity: 'UC',
    loreQuote: 'Uesugi Fuutarou! Today I shall claim first place on the national ranking board!',
    description: 'Takeda unfurling his exam results parchment with flair, only to find Fuutarou tied for first.',
    imageUrl: '/cards/Yusuke/yusuke 1.jpg',
  },
  {
    id: 'takeda_r_01',
    cardNumber: 'TQQ-050',
    characterId: 'takeda',
    characterRole: 'support',
    name: 'Yusuke Takeda',
    title: 'Honorable Competitor',
    rarity: 'R',
    loreQuote: 'A true gentleman acknowledges when he meets an equal. Let us strive for greatness together!',
    description: 'Takeda shaking Fuutarou\'s hand with magnanimous sportsmanship after the national finals.',
    imageUrl: '/cards/Yusuke/yusuke 1.jpg',
  },
];

// Lookup dictionaries for fast access
export const CARD_MAP: Record<string, CardDefinition> = CARDS_CATALOG.reduce(
  (acc, card) => {
    acc[card.id] = card;
    return acc;
  },
  {} as Record<string, CardDefinition>
);

export const CARDS_BY_RARITY: Record<Rarity, CardDefinition[]> = {
  C: CARDS_CATALOG.filter((c) => c.rarity === 'C'),
  UC: CARDS_CATALOG.filter((c) => c.rarity === 'UC'),
  R: CARDS_CATALOG.filter((c) => c.rarity === 'R'),
  SR: CARDS_CATALOG.filter((c) => c.rarity === 'SR'),
  UR: CARDS_CATALOG.filter((c) => c.rarity === 'UR'),
  SEC: CARDS_CATALOG.filter((c) => c.rarity === 'SEC'),
  MR: CARDS_CATALOG.filter((c) => c.rarity === 'MR'),
};

export const CARDS_BY_CHARACTER: Record<CharacterId, CardDefinition[]> = {
  ichika: CARDS_CATALOG.filter((c) => c.characterId === 'ichika'),
  nino: CARDS_CATALOG.filter((c) => c.characterId === 'nino'),
  miku: CARDS_CATALOG.filter((c) => c.characterId === 'miku'),
  yotsuba: CARDS_CATALOG.filter((c) => c.characterId === 'yotsuba'),
  itsuki: CARDS_CATALOG.filter((c) => c.characterId === 'itsuki'),
  fuutarou: CARDS_CATALOG.filter((c) => c.characterId === 'fuutarou'),
  raiha: CARDS_CATALOG.filter((c) => c.characterId === 'raiha'),
  maruo: CARDS_CATALOG.filter((c) => c.characterId === 'maruo'),
  isanari: CARDS_CATALOG.filter((c) => c.characterId === 'isanari'),
  takeda: CARDS_CATALOG.filter((c) => c.characterId === 'takeda'),
};

export function getCardDef(id: string): CardDefinition | undefined {
  return CARD_MAP[id];
}

export function getCardsByRarity(rarity: Rarity): CardDefinition[] {
  return CARDS_BY_RARITY[rarity] || [];
}

export function getCardsByCharacter(characterId: CharacterId): CardDefinition[] {
  return CARDS_BY_CHARACTER[characterId] || [];
}
